apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userApiIngress
  labels:
    app: userApiService
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - host: sau-portal.de
      http:
        paths:
          - path: /usermanagement
            pathType: Prefix
            backend:
              service:
                name: userApiService
                port:
                  number: 8000
