apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploy-to-k8s-demo
  labels:
    app: deploy-to-k8s-demo
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - host: sau-portal.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deploy-to-k8s-demo-service
                port:
                  number: 8000
