apiVersion: v1
kind: Service
metadata:
  name: user-api-service
  labels:
    app: user-api-service
spec:
  selector:
    app: user-api-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
