apiVersion: v1
kind: Service
metadata:
  name: deploy-to-k8s-demo
  labels:
    app: deploy-to-k8s-demo
spec:
  selector:
    app: deploy-to-k8s-demo
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
