apiVersion: v1
kind: Service
metadata:
  name: userApiService
  labels:
    app: userApiService
spec:
  selector:
    app: userApiApp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
